### ISSUE TITLE
Tracking testing results for Custom Groups 0.4.0

### ISSUE THREAD

**Issue by davitol** [owncloud/customgroups#190]
Tested using oC 10.0.10 version and  Custom Groups tarball located here: https://cloud.owncloud.com/index.php/s/sVIn0UDkELHe5vG

- [x] [Core platform switches to semver with 10.1](https://github.com/owncloud/core/pull/33242) so we set max-version to 10.1: https://github.com/owncloud/customgroups/pull/136
- [x] Small fixes: https://github.com/owncloud/customgroups/pull/165 **Tested with info provided in https://github.com/owncloud/customgroups/pull/165#issue-213687006**
- [x] PHP 7.2 support (confirmed only by tests, no code changes): https://github.com/owncloud/customgroups/pull/164 **CI is running in PHP 7.2**
