### ISSUE TITLE
Basic implementation

### ISSUE THREAD

**Issue by PVince81** [owncloud/customgroups#2]
## Goal
- Increase user acceptance of ownCloud service
- Improve ownCloud usability

## Basic Idea:
- Every user can create groups
- Every User can share with all existing groups

## Group Roles
- Roles: Groupadmin and Member
- All ownCloud Users can create groups and become groupadmin of this group

## Group Management
- User has overview of his groups (he is groupadmin)
- User has overview of his group memberships (he is member)
- User gets notification when added to group

As groupadmin, I can
- rename, delete group
- add, remove users to/from group
- set member / groupadmin role on group members
- not leave group if no groupadmin is left (but can delete group)

As member, I can
- see members of a group
- leave a group

ownCloud admins (who are in the "admin" group) can perform any operation that a group admin could.

### Core requirements

- [x] REQUIRES: https://github.com/owncloud/core/issues/26195 to allow apps to register Sabre plugins (because in the future all APIs are based on Webdav)
- [x] REQUIRES: support for group display names: https://github.com/owncloud/core/issues/7918

### Backend tasks

- [x] implement group backend for user groups: https://github.com/owncloud/customgroups/pull/1
- [x] new DB tables to store these groups: https://github.com/owncloud/customgroups/pull/1
- [x] generate unique group ids to avoid collisions: https://github.com/owncloud/customgroups/pull/1

- [x] Webdav APIs for group management: https://github.com/owncloud/customgroups/issues/3

- [x] transfer ownership must work with those
- [x] send notification when added to group: https://github.com/owncloud/customgroups/issues/4

### Frontend tasks

- [x] groups and membership management: https://github.com/owncloud/customgroups/issues/5

**Comment by PVince81** [comment]
- [ ] hide custom groups from users page: https://github.com/owncloud/customgroups/issues/6

**Comment by PVince81** [comment]
- [ ] pagination and quicksearch: https://github.com/owncloud/customgroups/issues/16

**Comment by PVince81** [comment]
- [ ] autocomplete for member field: https://github.com/owncloud/customgroups/issues/32

**Comment by PVince81** [comment]
All functionality of customgroups implemented in version v0.1.1.

The remaining things are more for scalability and user experience improvements, listed as separate tickets.
