### ISSUE TITLE
[strictly 10.8.0] Custom Groups 0.6.2

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/customgroups#416]
# Release 0.6.2

### Needed for:
- Implement UI and client handling for CSV import https://github.com/owncloud/customgroups/pull/415
- Use relative URLs instead of absolute URLs in Notifications https://github.com/owncloud/customgroups/pull/419

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) -> #438
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Changelog item #415 tested
    - [x] Changelog item #419 tested
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [ ] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10-0)  and [new portal](https://portal.owncloud.com) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by micbar** [comment]
@jnweiger This was lying around and wasn't fed to the default process for 7 weeks now.

Now we have a "silent prio escalation"

1) We need a signed rc for the customer -> Prio: P2-High
2) After that, Prio is back to normal.

**Comment by jnweiger** [comment]
https://github.com/owncloud/enterprise/issues/4394

**Comment by jnweiger** [comment]
Signed beta done: https://github.com/owncloud/customgroups/releases/tag/v0.6.2-beta2
Back to 'in dev', removing p2.

**Comment by micbar** [comment]
RC1 in https://github.com/owncloud/customgroups/releases/tag/v0.6.2RC1

**Comment by JanAckermann** [comment]
Issues while testing:

https://github.com/owncloud/customgroups/issues/440
https://github.com/owncloud/customgroups/issues/441 (Breaker)
https://github.com/owncloud/customgroups/issues/444

**Comment by JanAckermann** [comment]
@micbar RC2 needed

**Comment by micbar** [comment]
RC2 in https://github.com/owncloud/customgroups/releases/tag/v0.6.2RC2
