### ISSUE TITLE
Add more test coverage to apiCustomGroups

### ISSUE THREAD

**Issue by phil-davis** [owncloud/customgroups#425]
Add some test scenarios to cover:
- [x] combinations of sharing when there is an ordinary group name and custom group names that are the same (similar to issue #401 but use the API) done in #427
- [x] combinations of sharing when a folder is shared with an ordinary user/group and sub-folder shared with a custom group. done in #427
- [x] combinations of sharing when a folder is shared with an custom group and sub-folder shared with an ordinary user/group group. done in #427 
- [x] resharing of a received custom group share by the share receiver - done in #427 
- [x] trying to leave a custom group if you have already left it (see issue #414 ) done in #427

**Comment by phil-davis** [comment]
PR #427 has been merged.
@SwikritiT I think this issue is finished?
