### ISSUE TITLE
0.3.5 release checklist

### ISSUE THREAD

**Issue by felixboehm** [owncloud/customgroups#76]
Release needed for https://github.com/owncloud/enterprise/issues/2092#issuecomment-321470519, amongst others.

Development, Open must have for release 
- [x] #77 
- [x] changelog https://github.com/owncloud/customgroups/pull/83

QA
- [x] create "0.3.4 Testplan", link: https://github.com/owncloud/customgroups/issues/86

Marketing
- [x] Check/adapt info.xml stuff https://github.com/owncloud/customgroups/pull/104
- [ ] Check/adapt screenshot @hurradieweltgehtunter 

Build

- [x] bump version in info.xml => https://github.com/owncloud/customgroups/pull/111
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section => https://github.com/owncloud/customgroups/pull/111
- [x] sign and build tarball
- [x] upload to marketplace
- [x] rename QA milestone to '$version'

**Comment by PVince81** [comment]
I've set the code freeze date to July 7th as there is at least one open task. I'll set that one to "development" as well.

**Comment by PVince81** [comment]
ok I see that already a few tickets were set to "development". I'm not sure whether we should do them all right now or later.

There are already many changes in the current master which I think would be good to release first.
Then we can think whether we want to invest time in the other "development" item.

The only one I'd keep is https://github.com/owncloud/customgroups/pull/74

**Comment by PVince81** [comment]
turns out we also have https://github.com/owncloud/customgroups/issues/77 which is a p1

**Comment by PVince81** [comment]
last PR was merged, QA can be scheduled

**Comment by PVince81** [comment]
- [ ] set min-version to 10.0.3 once core is out (this is not a hard requirement, it just fixes an issue to make sure error message is displayed properly)

**Comment by PVince81** [comment]
Setting release date (code freeze date) to august 25th.

**Comment by PVince81** [comment]
added changelog PR: https://github.com/owncloud/customgroups/pull/83

**Comment by PVince81** [comment]
- [ ] updated changelog, as we fixed more stuff: https://github.com/owncloud/customgroups/pull/109

**Comment by PVince81** [comment]
- [ ] one more fix to merge (security-related): https://github.com/owncloud/customgroups/pull/92

**Comment by PVince81** [comment]
- [ ] some issue with icon not appearing in @SergioBertolinSG's env, under investigation

**Comment by PVince81** [comment]
bumping version in https://github.com/owncloud/customgroups/pull/111, don't merge yet

**Comment by PVince81** [comment]
tagged, will build and sign tarball

**Comment by PVince81** [comment]
tarball here: https://github.com/owncloud/customgroups/releases/download/v0.3.5/customgroups.tar.gz

**Comment by PVince81** [comment]
@DeepDiver1975 please push to marketplace, thanks. Tarball is signed already.

**Comment by PVince81** [comment]
already on the marketplace, closing
